#!/usr/bin/env python3
"""
Generate docs/INDEX.md — a flat, single-file map of every doc under docs/:
title, a one-line summary, and its outbound links. Not a lint check (doesn't
fail the build); run it manually or alongside `docs_lint.py --link-graph`
whenever the docs corpus changes meaningfully.

Usage:
  python3 scripts/generate_docs_index.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from docs_lint import _markdown_files, _iter_markdown_links, build_link_graph  # noqa: E402

_TITLE = re.compile(r"^#\s+(.+)$", re.MULTILINE)
_SKIP_LINE = re.compile(
    r"^\s*(\*\*[A-Za-z ]+:\*\*|>|#|\|.*\||```)"  # metadata fields, banners, headings, tables, fences
)


def _extract_title(text: str) -> str:
    match = _TITLE.search(text)
    return match.group(1).strip() if match else "(untitled)"


def _extract_summary(text: str, max_len: int = 200) -> str:
    """First substantive paragraph after the title — skips metadata fields
    (**Owner:** etc.), historical banners (> ...), and headings."""
    lines = text.splitlines()
    started_body = False
    paragraph: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not started_body:
            if stripped.startswith("# "):
                started_body = True
            continue
        if not stripped:
            if paragraph:
                break
            continue
        if _SKIP_LINE.match(line):
            continue
        paragraph.append(stripped)
    summary = " ".join(paragraph)
    # Rewrite [text](target) to just the text: source-relative link targets
    # don't resolve from docs/INDEX.md and would trip DOC-007.
    summary = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", summary)
    if len(summary) > max_len:
        summary = summary[: max_len - 1].rsplit(" ", 1)[0] + "…"
    return summary or "(no summary — see file)"


def generate(repo_root: Path) -> str:
    forward: dict[str, list[str]] = {}
    for rel_path, _target, resolved_rel in _iter_markdown_links(repo_root):
        if resolved_rel is None or resolved_rel == rel_path:
            continue
        forward.setdefault(rel_path, [])
        if resolved_rel not in forward[rel_path]:
            forward[rel_path].append(resolved_rel)

    entries = []
    for path in _markdown_files(repo_root):
        rel_path = path.relative_to(repo_root).as_posix()
        text = path.read_text(encoding="utf-8", errors="ignore")
        entries.append(
            {
                "path": rel_path,
                "title": _extract_title(text),
                "summary": _extract_summary(text),
                "links": sorted(forward.get(rel_path, [])),
            }
        )
    entries.sort(key=lambda e: e["path"])

    lines = [
        "# Documentation Index",
        "",
        "> Generated by `scripts/generate_docs_index.py` — do not hand-edit; re-run the script instead.",
        "> Flat repo-map: every doc's title, a one-line summary, and its outbound links, so an agent",
        "> (or a human) can get the whole map from one file instead of re-deriving structure each session.",
        "> For reverse links (\"what links here?\"), see `docs/_link_graph.json`",
        "> (`python3 scripts/docs_lint.py --link-graph`).",
        "",
    ]
    for entry in entries:
        lines.append(f"## `{entry['path']}`")
        lines.append("")
        lines.append(f"**{entry['title']}**")
        lines.append("")
        lines.append(entry["summary"])
        if entry["links"]:
            lines.append("")
            lines.append("Links to: " + ", ".join(f"`{link}`" for link in entry["links"]))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def check(repo_root: Path) -> int:
    index_path = repo_root / "docs" / "INDEX.md"
    graph_path = repo_root / "docs" / "_link_graph.json"

    expected_index = generate(repo_root)
    actual_index = _read_text(index_path)
    expected_graph = build_link_graph(repo_root)
    actual_graph = json.loads(_read_text(graph_path))

    stale = False
    if actual_index != expected_index:
        stale = True
        print("docs/INDEX.md is stale.")
    if actual_graph != expected_graph:
        stale = True
        print("docs/_link_graph.json is stale.")
    if stale:
        print(
            "Regenerate with: python3 scripts/generate_docs_index.py && python3 scripts/docs_lint.py --link-graph"
        )
        return 1
    print("docs/INDEX.md and docs/_link_graph.json are fresh.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or verify docs/INDEX.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify docs/INDEX.md and docs/_link_graph.json are up to date",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    if args.check:
        return check(repo_root)

    content = generate(repo_root)
    dest = repo_root / "docs" / "INDEX.md"
    dest.write_text(content, encoding="utf-8")
    print(f"Wrote {dest.relative_to(repo_root)} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
